"""Replay governed SafeMPPI references through the calibrated deployment plant.

This is intentionally open loop with respect to the planner: no SafeMPPI
replanning occurs.  It isolates position-tracking error by streaming the stored
reference generated by an accepted demonstration into the unchanged
``deploy_sim`` plant.
"""
from __future__ import annotations

import numpy as np

from deploy_sim.harness import geofence
from deploy_sim.plant import Swarm

from .environment import TaskEnvironment


def command_box(config, env: TaskEnvironment, margin: float = 0.25) -> np.ndarray:
    """Reproduce the deployment harness's commanded-position clipping box."""
    soft, _ = geofence(config, env, env.start, env.goal)
    box = np.stack([soft[:, 0] + margin, soft[:, 1] - margin], axis=1)
    for point in (env.start[:3], env.goal):
        box[:, 0] = np.minimum(box[:, 0], point)
        box[:, 1] = np.maximum(box[:, 1], point)
    return box


def _minimum_box_margin(points: np.ndarray, box: np.ndarray) -> float:
    points = np.asarray(points, float).reshape(-1, 3)
    return float(np.min(np.minimum(
        points - box[:, 0],
        box[:, 1] - points,
    )))


def replay_demo_on_plant(
    config,
    dense_reference_positions: np.ndarray,
    executed_controls: np.ndarray,
    *,
    seed: int,
    clip_commanded_position: bool = False,
    command_margin: float = 0.25,
    current_state_position_weight: float = 0.0,
) -> dict[str, np.ndarray | float | bool | None]:
    """Stream one stored governed reference through the deployment plant.

    ``dense_reference_positions`` and ``executed_controls`` are already the
    output of the reference governor.  They are streamed without applying
    smoothing or clipping a second time.
    """
    env = TaskEnvironment(config)
    dense_reference_positions = np.asarray(
        dense_reference_positions, np.float32,
    ).reshape(-1, 3)
    executed_controls = np.asarray(
        executed_controls, np.float32,
    ).reshape(-1, 3)
    if not 0.0 <= current_state_position_weight < 1.0:
        raise ValueError("current_state_position_weight must lie in [0,1)")
    substeps = config.safemppi.integration_substeps
    expected_positions = 1 + len(executed_controls) * substeps
    if len(dense_reference_positions) != expected_positions:
        raise ValueError(
            "dense reference must contain one initial point plus "
            "integration_substeps points per executed control"
        )

    swarm = Swarm(dense_reference_positions[0], seed=int(seed))
    clock = swarm.timeHelper
    plant = swarm.allcfs.crazyflies[0]
    box = command_box(config, env, margin=command_margin)
    dt_sub = config.safemppi.dt / substeps
    reference_positions_input = dense_reference_positions[1:]
    reference_velocities_input = np.diff(
        dense_reference_positions, axis=0,
    ) / dt_sub
    applied_controls_input = np.repeat(
        executed_controls, substeps, axis=0,
    )

    times = []
    reference_positions = []
    commanded_positions = []
    reference_velocities = []
    applied_controls = []
    true_positions = []
    estimated_positions = []
    measured_positions = []
    true_velocities = []
    command_anchor_positions = []
    current_measured_position = np.asarray(plant.position(), np.float32)

    for reference_position, reference_velocity, applied in zip(
        reference_positions_input,
        reference_velocities_input,
        applied_controls_input,
    ):
        commanded_position = (
            current_state_position_weight * current_measured_position
            + (1.0 - current_state_position_weight) * reference_position
        )
        if clip_commanded_position:
            commanded_position = np.clip(
                commanded_position, box[:, 0], box[:, 1],
            )
        plant.cmdFullState(
            commanded_position.tolist(),
            reference_velocity.tolist(),
            applied.tolist(),
            0.0,
            [0.0, 0.0, 0.0],
        )
        clock.sleep(dt_sub)
        times.append(clock.time())
        reference_positions.append(reference_position.copy())
        commanded_positions.append(commanded_position.copy())
        reference_velocities.append(reference_velocity.copy())
        applied_controls.append(applied.copy())
        command_anchor_positions.append(current_measured_position.copy())
        true_positions.append(plant.p.copy())
        estimated_positions.append(plant.p_est.copy())
        current_measured_position = np.asarray(plant.position(), np.float32)
        measured_positions.append(current_measured_position.copy())
        true_velocities.append(plant.v.copy())

    reference_positions = np.asarray(reference_positions, np.float32)
    commanded_positions = np.asarray(commanded_positions, np.float32)
    reference_velocities = np.asarray(reference_velocities, np.float32)
    applied_controls = np.asarray(applied_controls, np.float32)
    true_positions = np.asarray(true_positions, np.float32)
    estimated_positions = np.asarray(estimated_positions, np.float32)
    measured_positions = np.asarray(measured_positions, np.float32)
    true_velocities = np.asarray(true_velocities, np.float32)
    command_anchor_positions = np.asarray(
        command_anchor_positions, np.float32,
    )
    times = np.asarray(times, np.float64)

    reference_clearance = env.obstacle_clearance(reference_positions)
    plant_clearance = env.obstacle_clearance(true_positions)
    soft, hard = geofence(config, env, env.start, env.goal)
    true_soft_margin = _minimum_box_margin(true_positions, soft)
    measured_soft_margin = _minimum_box_margin(measured_positions, soft)
    true_hard_margin = _minimum_box_margin(true_positions, hard)
    measured_hard_margin = _minimum_box_margin(measured_positions, hard)
    reference_goal_distances = np.linalg.norm(
        reference_positions - env.goal, axis=1,
    )
    reference_reached = bool(np.any(
        reference_goal_distances < env.task.reach_radius
    ))
    reference_collision = bool(
        np.isfinite(reference_clearance).any()
        and float(np.nanmin(reference_clearance)) < 0.0
    )
    reference_taskspace_violation = bool(
        not env.inside_taskspace(reference_positions).all()
    )
    reference_success = bool(
        reference_reached
        and not reference_collision
        and not reference_taskspace_violation
    )
    goal_distances = np.linalg.norm(true_positions - env.goal, axis=1)
    reached_indices = np.flatnonzero(goal_distances < env.task.reach_radius)
    collision = bool(np.isfinite(plant_clearance).any()
                     and float(np.nanmin(plant_clearance)) < 0.0)
    taskspace_violation = bool(not env.inside_taskspace(true_positions).all())
    reached = bool(len(reached_indices))
    geometric_success = bool(
        reached and not collision and not taskspace_violation
    )
    clipped = np.linalg.norm(
        commanded_positions - reference_positions, axis=1,
    ) > 1.0e-8
    raw_reference_tracking_error = true_positions - reference_positions
    command_tracking_error = true_positions - commanded_positions
    reference_command_error = commanded_positions - reference_positions

    return {
        "time": times,
        "reference_positions": reference_positions,
        "commanded_positions": commanded_positions,
        "reference_velocities": reference_velocities,
        "applied_controls": applied_controls,
        "plant_positions": true_positions,
        "estimated_positions": estimated_positions,
        "measured_positions": measured_positions,
        "plant_velocities": true_velocities,
        "command_anchor_positions": command_anchor_positions,
        "reference_success": reference_success,
        "reference_reached": reference_reached,
        "reference_collision": reference_collision,
        "reference_taskspace_violation": reference_taskspace_violation,
        "geometric_success": geometric_success,
        "reached": reached,
        "collision": collision,
        "taskspace_violation": taskspace_violation,
        "true_soft_geofence_violation": bool(true_soft_margin < 0.0),
        "measured_soft_geofence_violation": bool(
            measured_soft_margin < 0.0
        ),
        "true_hard_geofence_violation": bool(true_hard_margin < 0.0),
        "measured_hard_geofence_violation": bool(
            measured_hard_margin < 0.0
        ),
        "reference_min_clearance_m": (
            float(np.nanmin(reference_clearance))
            if np.isfinite(reference_clearance).any() else None
        ),
        "plant_min_clearance_m": (
            float(np.nanmin(plant_clearance))
            if np.isfinite(plant_clearance).any() else None
        ),
        "minimum_true_soft_geofence_margin_m": true_soft_margin,
        "minimum_measured_soft_geofence_margin_m": measured_soft_margin,
        "minimum_true_hard_geofence_margin_m": true_hard_margin,
        "minimum_measured_hard_geofence_margin_m": measured_hard_margin,
        "raw_reference_tracking_rmse_m": float(np.sqrt(np.mean(np.sum(
            raw_reference_tracking_error ** 2, axis=1,
        )))),
        "raw_reference_tracking_max_error_m": float(
            np.linalg.norm(raw_reference_tracking_error, axis=1).max()
        ),
        "command_tracking_rmse_m": float(np.sqrt(np.mean(np.sum(
            command_tracking_error ** 2, axis=1,
        )))),
        "command_tracking_max_error_m": float(
            np.linalg.norm(command_tracking_error, axis=1).max()
        ),
        "reference_command_rmse_m": float(np.sqrt(np.mean(np.sum(
            reference_command_error ** 2, axis=1,
        )))),
        "command_clip_fraction": float(clipped.mean()),
        "current_state_position_weight": float(
            current_state_position_weight
        ),
        "peak_reference_speed_mps": float(
            np.linalg.norm(reference_velocities, axis=1).max()
        ),
        "peak_plant_speed_mps": float(
            np.linalg.norm(true_velocities, axis=1).max()
        ),
        "peak_abs_plant_vertical_speed_mps": float(
            np.abs(true_velocities[:, 2]).max()
        ),
        "max_abs_applied_acceleration_mps2": float(
            np.abs(applied_controls).max()
        ),
        "time_to_goal_s": (
            float(times[reached_indices[0]]) if reached else None
        ),
    }
