#!/usr/bin/env python3
"""Build provenance-bound Stage-1 handoff trajectory figures for Minhyuk.

The script is intentionally evaluation-only. It renders the two selected
exact-five SafeMPPI route-diversity candidates and replays the promoted visual
checkpoint with the canonical raw temperature-1 controller. Every trajectory
shown was generated by the checked-in implementation.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from itertools import combinations
import math
from pathlib import Path
import subprocess
import sys

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation, PillowWriter
from matplotlib.patches import Circle
import numpy as np
import torch


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from safe_mppi.config import load_config  # noqa: E402
from safe_mppi.ball_analysis import draw_polytope_soft  # noqa: E402
from safe_mppi.environment import TaskEnvironment  # noqa: E402
from safe_mppi.lab_clutter import ClutterScene, config_for_scene  # noqa: E402
from safe_mppi.lab_reference_flow_task import raw_reference_rollout  # noqa: E402
from safe_mppi.lab_visual_flow import load_lab_reference_policy  # noqa: E402
from safe_mppi.path_focused_clutter import path_focused_scene_bank  # noqa: E402
from safe_mppi.visualize import _poly_from_saved  # noqa: E402


GAMMAS = (0.1, 0.3, 0.5, 1.0)
GAMMA_COLORS = {
    gamma: plt.get_cmap("plasma")(0.08 + 0.84 * index / 3.0)
    for index, gamma in enumerate(GAMMAS)
}
EXPECTED_STAGE1_COUNTS = {
    "SUCCESS": 11,
    "COLLISION": 64,
    "OOB": 5,
    "TIMEOUT": 0,
}
EXPECTED_THREE_SPHERE_HASH = (
    "82eb7361927f8d076a6a7fc7a3f52e17f4ff9d203b4af49ca532ceffa2afd0c3"
)
EXACT_FIVE_CANDIDATES = (
    {
        "key": "E",
        "scene_id": "cylinders_00317",
        "scene_hash": (
            "eaf81f1e663f5f88604940a208b002ad609021e4d9d365e6b5781e3a6dcafb81"
        ),
        "scene_seed": 640_760_290,
        "rollout_seed": 729_853,
        "route_signature_count": 3,
    },
    {
        "key": "F",
        "scene_id": "cylinders_01652",
        "scene_hash": (
            "b125cea117babdf4966ca8b1e131ef7f424914127a385ba8736c68bd05c05097"
        ),
        "scene_seed": 650_346_658,
        "rollout_seed": 2_076_868,
        "route_signature_count": 3,
    },
)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _write_handoff_checksums(handoff_dir: Path) -> Path:
    destination = handoff_dir / "SHA256SUMS"
    files = sorted(
        path for path in handoff_dir.rglob("*")
        if path.is_file() and path != destination
    )
    destination.write_text("".join(
        f"{_sha256(path)}  {path.relative_to(ROOT)}\n" for path in files
    ))
    return destination


def _git_revision(ref: str) -> str | None:
    completed = subprocess.run(
        ["git", "rev-parse", ref],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    return completed.stdout.strip() if completed.returncode == 0 else None


def _dense_path(result: dict) -> np.ndarray:
    states = np.asarray(result["states"], np.float32)
    dense = np.asarray(result["dense_steps"], np.float32)
    if not len(dense):
        return states[:, :3]
    return np.concatenate([states[:1, :3], dense.reshape(-1, 3)])


def _first_failure_point(result: dict, config) -> list[float] | None:
    if result["status"] == "SUCCESS":
        return None
    path = _dense_path(result)
    env = TaskEnvironment(config)
    if result["status"] == "COLLISION":
        clearance = env.obstacle_clearance(path)
        indices = np.flatnonzero(np.isfinite(clearance) & (clearance < 0.0))
    elif result["status"] == "OOB":
        indices = np.flatnonzero(~env.inside_taskspace(path))
    else:
        indices = np.asarray([len(path) - 1], dtype=np.int64)
    index = int(indices[0]) if len(indices) else len(path) - 1
    return [float(value) for value in path[index]]


def _arc_resample(path: np.ndarray, count: int = 96) -> np.ndarray:
    path = np.asarray(path, np.float64).reshape(-1, 3)
    keep = np.r_[True, np.linalg.norm(np.diff(path, axis=0), axis=1) > 1e-10]
    path = path[keep]
    if len(path) == 1:
        return np.repeat(path, count, axis=0)
    distance = np.r_[0.0, np.cumsum(np.linalg.norm(np.diff(path, axis=0), axis=1))]
    query = np.linspace(0.0, distance[-1], count)
    return np.column_stack([
        np.interp(query, distance, path[:, axis]) for axis in range(3)
    ])


def _cross_gamma_spread(paths: list[np.ndarray]) -> float:
    sampled = [_arc_resample(path) for path in paths]
    values = [
        np.sqrt(np.mean(np.sum((sampled[left] - sampled[right]) ** 2, axis=1)))
        for left, right in combinations(range(len(sampled)), 2)
    ]
    return float(np.mean(values))


def _draw_cylinders(axis, cylinders: np.ndarray, z_bounds, physical_radius: float):
    theta = np.linspace(0.0, 2.0 * np.pi, 36)
    theta_grid, z_grid = np.meshgrid(theta, np.asarray(z_bounds, np.float64))
    for x, y, modeled_radius in np.asarray(cylinders, np.float64).reshape(-1, 3):
        axis.plot_wireframe(
            x + modeled_radius * np.cos(theta_grid),
            y + modeled_radius * np.sin(theta_grid),
            z_grid,
            color="#2b8cbe",
            alpha=0.30,
            linewidth=0.55,
        )
        axis.plot_surface(
            x + physical_radius * np.cos(theta_grid),
            y + physical_radius * np.sin(theta_grid),
            z_grid,
            color="#747b80",
            alpha=0.62,
            linewidth=0.0,
            shade=True,
        )


def _draw_cylinders_top(
    axis,
    cylinders: np.ndarray,
    *,
    physical_radius: float,
):
    for x, y, modeled_radius in np.asarray(
        cylinders, np.float64,
    ).reshape(-1, 3):
        axis.add_patch(Circle(
            (x, y), modeled_radius, fill=False, edgecolor="#2b8cbe",
            linestyle="--", linewidth=1.0, alpha=0.62,
        ))
        axis.add_patch(Circle(
            (x, y), physical_radius, facecolor="#747b80",
            edgecolor="#555b60", linewidth=0.45, alpha=0.70,
        ))


def _style_top_axis(axis, config):
    axis.set(
        xlim=config.taskspace.bounds[0],
        ylim=config.taskspace.bounds[1],
        xlabel=r"$x$ [m]",
        ylabel=r"$y$ [m]",
        aspect="equal",
    )
    axis.grid(alpha=0.18)
    axis.tick_params(labelsize=8)


def _start_goal_top(axis, config):
    axis.scatter(
        *config.taskspace.start[:2], marker="s", s=42, color="black",
        zorder=20,
    )
    axis.scatter(
        *config.taskspace.goal[:2], marker="*", s=145, color="#f1c40f",
        edgecolor="black", linewidth=0.7, zorder=20,
    )


def _horizontal_detour_metrics(path: np.ndarray, config) -> dict:
    path_xy = np.asarray(path, np.float64).reshape(-1, 3)[:, :2]
    start = np.asarray(config.taskspace.start[:2], np.float64)
    goal = np.asarray(config.taskspace.goal[:2], np.float64)
    direction = goal - start
    direct_distance = float(np.linalg.norm(direction))
    if direct_distance <= 0.0:
        raise ValueError("start and goal must be distinct")
    unit = direction / direct_distance
    transverse = np.asarray([-unit[1], unit[0]])
    signed_cross_track = (path_xy - start[None]) @ transverse
    path_length = float(np.linalg.norm(np.diff(path_xy, axis=0), axis=1).sum())
    endpoint_direct = float(np.linalg.norm(path_xy[-1] - path_xy[0]))
    return {
        "horizontal_transverse_rms_m": float(
            np.sqrt(np.mean(signed_cross_track ** 2))
        ),
        "horizontal_max_abs_cross_track_m": float(
            np.max(np.abs(signed_cross_track))
        ),
        "horizontal_path_length_m": path_length,
        "horizontal_path_inefficiency_m": path_length - endpoint_direct,
        "mean_signed_cross_track_m": float(np.mean(signed_cross_track)),
    }


def _draw_spheres(axis, spheres: np.ndarray, physical_radius: float):
    azimuth = np.linspace(0.0, 2.0 * np.pi, 32)
    polar = np.linspace(0.0, np.pi, 18)
    unit_x = np.outer(np.cos(azimuth), np.sin(polar))
    unit_y = np.outer(np.sin(azimuth), np.sin(polar))
    unit_z = np.outer(np.ones_like(azimuth), np.cos(polar))
    for x, y, z, modeled_radius in np.asarray(spheres, np.float64).reshape(-1, 4):
        axis.plot_wireframe(
            x + modeled_radius * unit_x,
            y + modeled_radius * unit_y,
            z + modeled_radius * unit_z,
            color="#2b8cbe",
            alpha=0.32,
            linewidth=0.5,
        )
        axis.plot_surface(
            x + physical_radius * unit_x,
            y + physical_radius * unit_y,
            z + physical_radius * unit_z,
            color="#747b80",
            alpha=0.66,
            linewidth=0.0,
            shade=True,
        )


def _style_axis(axis, config, *, elev: float = 25.0, azim: float = -57.0):
    axis.set(
        xlim=config.taskspace.bounds[0],
        ylim=config.taskspace.bounds[1],
        zlim=config.taskspace.bounds[2],
        xlabel=r"$x$ [m]",
        ylabel=r"$y$ [m]",
        zlabel=r"$z$ [m]",
    )
    axis.view_init(elev=elev, azim=azim)
    axis.grid(alpha=0.18)
    axis.tick_params(labelsize=8)


def _start_goal(axis, config):
    axis.scatter(
        *config.taskspace.start[:3], marker="s", s=42, color="black",
        depthshade=False, zorder=20,
    )
    axis.scatter(
        *config.taskspace.goal, marker="*", s=145, color="#f1c40f",
        edgecolor="black", linewidth=0.7, depthshade=False, zorder=20,
    )


def _save_figure(fig, destination: Path):
    destination.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(destination, dpi=210, bbox_inches="tight")
    fig.savefig(
        destination.with_suffix(".pdf"),
        bbox_inches="tight",
        metadata={"Creator": "safeMPPI_demo_3d", "CreationDate": None},
    )
    plt.close(fig)


def _nominal_polytope_gif(
    archive: dict,
    destination: Path,
    config,
    *,
    gamma: float,
    physical_radius: float,
    candidate_label: str,
) -> dict:
    dense = np.asarray(archive["dense_positions"], np.float32)
    states = np.asarray(archive["states"], np.float32)
    controls = np.asarray(archive["controls"], np.float32)
    cylinders = np.asarray(archive["cylinders"], np.float32)
    horizon_steps = len(controls)
    if horizon_steps <= 0 or (len(dense) - 1) % horizon_steps:
        raise RuntimeError("dense SafeMPPI archive does not have fixed substeps")
    dense_substeps = (len(dense) - 1) // horizon_steps
    if len(archive["poly_A"]) != horizon_steps or len(archive["poly_b"]) != horizon_steps:
        raise RuntimeError("nominal-polytope history length does not match controls")
    stride = max(1, math.ceil(horizon_steps / 40))
    render_steps = list(range(0, horizon_steps + 1, stride))
    if render_steps[-1] != horizon_steps:
        render_steps.append(horizon_steps)

    fig = plt.figure(figsize=(10.6, 4.7), facecolor="white")
    axis_3d = fig.add_subplot(1, 2, 1, projection="3d")
    axis_top = fig.add_subplot(1, 2, 2)

    def draw(frame_index: int):
        step = render_steps[frame_index]
        poly_index = min(step, horizon_steps - 1)
        dense_end = min(len(dense), 1 + dense_substeps * step)
        visible = dense[:dense_end]
        axis_3d.clear()
        axis_top.clear()

        _draw_cylinders(
            axis_3d, cylinders, config.taskspace.bounds[2], physical_radius,
        )
        polytope = _poly_from_saved(archive, poly_index)
        if np.any(polytope.margins <= 0.0):
            raise RuntimeError(
                f"saved nominal polytope is not strict-interior at step {poly_index}"
            )
        draw_polytope_soft(axis_3d, polytope, gamma)
        axis_3d.plot(
            visible[:, 0], visible[:, 1], visible[:, 2],
            color=GAMMA_COLORS[gamma], linewidth=2.7,
        )
        axis_3d.scatter(
            *states[step, :3], color="#1665a7", s=30, depthshade=False,
            zorder=30,
        )
        _start_goal(axis_3d, config)
        _style_axis(axis_3d, config)
        axis_3d.set_box_aspect(
            tuple(config.taskspace.bounds[:, 1] - config.taskspace.bounds[:, 0])
        )
        axis_3d.set_title("Perspective + nominal level sets", fontsize=11)

        _draw_cylinders_top(
            axis_top, cylinders, physical_radius=physical_radius,
        )
        axis_top.plot(
            visible[:, 0], visible[:, 1],
            color=GAMMA_COLORS[gamma], linewidth=2.7,
        )
        axis_top.scatter(
            *states[step, :2], color="#1665a7", s=28, zorder=30,
        )
        _start_goal_top(axis_top, config)
        _style_top_axis(axis_top, config)
        axis_top.set_title("Top view", fontsize=11)
        fig.suptitle(
            rf"Exact-five candidate {candidate_label} | $\gamma={gamma:g}$ | "
            rf"step {step}/{horizon_steps}",
            fontsize=14,
        )
        return []

    animation = FuncAnimation(
        fig, draw, frames=len(render_steps), interval=125, blit=False,
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    animation.save(
        destination,
        writer=PillowWriter(fps=8),
        dpi=92,
        savefig_kwargs={"facecolor": "white"},
    )
    plt.close(fig)
    return {
        "path": str(destination.relative_to(destination.parents[1])),
        "frames": len(render_steps),
        "fps": 8,
        "dense_substeps_per_control": dense_substeps,
        "bytes": destination.stat().st_size,
        "sha256": _sha256(destination),
    }


def _route_signatures(paths: list[np.ndarray], cylinders: np.ndarray, config):
    start = np.asarray(config.taskspace.start[:2], np.float64)
    goal = np.asarray(config.taskspace.goal[:2], np.float64)
    longitudinal = goal - start
    longitudinal /= np.linalg.norm(longitudinal)
    transverse = np.asarray([-longitudinal[1], longitudinal[0]])
    centers = np.asarray(cylinders, np.float64).reshape(-1, 3)[:, :2]
    obstacle_s = (centers - start[None]) @ longitudinal
    obstacle_t = (centers - start[None]) @ transverse
    signatures = []
    for path in paths:
        xy = np.asarray(path, np.float64).reshape(-1, 3)[:, :2]
        path_s = (xy - start[None]) @ longitudinal
        path_t = (xy - start[None]) @ transverse
        signature = []
        for target_s, target_t in zip(obstacle_s, obstacle_t):
            index = int(np.argmin(np.abs(path_s - target_s)))
            delta = float(path_t[index] - target_t)
            signature.append(1 if delta > 0.03 else (-1 if delta < -0.03 else 0))
        signatures.append(tuple(signature))
    return signatures


def _expert_candidate(
    handoff_dir: Path,
    output_dir: Path,
    config_path: Path,
    candidate: dict,
) -> dict:
    config = load_config(config_path)
    archive_dir = handoff_dir / "trajectory_archives"
    candidate_key = str(candidate["key"])
    scene_id = str(candidate["scene_id"])
    scene_hash_expected = str(candidate["scene_hash"])
    scene_seed_expected = int(candidate["scene_seed"])
    rollout_seed = int(candidate["rollout_seed"])
    rows = []
    paths = []
    archives = []
    scene_hashes = set()
    cylinders = None
    physical_radius = float(config.raw["scene_randomization"]["physical_radius_m"])
    for gamma in GAMMAS:
        label = "1" if gamma == 1.0 else f"{gamma:g}"
        path = archive_dir / (
            f"run_g{label}_{scene_id}_s{rollout_seed}.npz"
        )
        with np.load(path, allow_pickle=True) as data:
            archive = {key: data[key] for key in data.files}
        dense = np.asarray(archive["dense_positions"], np.float32)
        states = np.asarray(archive["states"], np.float32)
        current_cylinders = np.asarray(archive["cylinders"], np.float32)
        scene = ClutterScene(
            index=int(archive["scene_index"]),
            seed=int(archive["scene_seed"]),
            spheres=(),
            cylinders=tuple(tuple(map(float, row)) for row in current_cylinders),
            scene_hash=str(archive["scene_hash"].item()),
        )
        env = TaskEnvironment(config_for_scene(config, scene))
        goal = np.asarray(config.taskspace.goal, np.float64)
        reached = bool(np.any(
            np.linalg.norm(states[:, :3] - goal[None], axis=1)
            <= config.taskspace.reach_radius
        ))
        collision = bool(np.any(env.obstacle_clearance(dense) < 0.0))
        out_of_bounds = bool(np.any(~env.inside_taskspace(dense)))
        status = (
            "SUCCESS" if reached and not collision and not out_of_bounds
            else "FAILURE"
        )
        if status != "SUCCESS":
            raise RuntimeError(f"expert archive is not a terminal success: {path}")
        if not np.isclose(float(archive["gamma"]), gamma, atol=2e-7):
            raise RuntimeError(f"expert archive gamma mismatch: {path}")
        if int(archive["seed"]) != rollout_seed:
            raise RuntimeError(f"expert archive rollout seed mismatch: {path}")
        if str(archive["scene_id"].item()) != scene_id:
            raise RuntimeError(f"expert archive scene id mismatch: {path}")
        scene_hash = str(archive["scene_hash"].item())
        if scene_hash != scene_hash_expected:
            raise RuntimeError(f"expert archive scene hash mismatch: {path}")
        if int(archive["scene_seed"]) != scene_seed_expected:
            raise RuntimeError(f"expert archive scene seed mismatch: {path}")
        if current_cylinders.shape != (5, 3):
            raise RuntimeError(f"expert evidence must contain exactly five cylinders: {path}")
        scene_hashes.add(scene_hash)
        if cylinders is None:
            cylinders = current_cylinders
        elif not np.array_equal(cylinders, current_cylinders):
            raise RuntimeError("expert overlay archives do not share one scene")
        paths.append(dense)
        archives.append(archive)
        detour = _horizontal_detour_metrics(dense, config)
        rows.append({
            "gamma": gamma,
            "status": status,
            "seed": int(archive["seed"]),
            "scene_id": str(archive["scene_id"].item()),
            "scene_seed": int(archive["scene_seed"]),
            "scene_hash": scene_hash,
            "steps": int(len(archive["controls"])),
            "time_to_goal_s": float(len(archive["controls"]) * config.safemppi.dt),
            "goal_distance_m": float(
                np.min(np.linalg.norm(states[:, :3] - goal[None], axis=1))
            ),
            "min_clearance_m": float(np.min(env.obstacle_clearance(dense))),
            **detour,
            "archive": str(path.relative_to(ROOT)),
            "archive_sha256": _sha256(path),
        })
    if len(scene_hashes) != 1:
        raise RuntimeError("expert overlay archives have inconsistent scene hashes")
    signatures = _route_signatures(paths, cylinders, config)
    route_signature_count = len(set(signatures))
    if route_signature_count != int(candidate["route_signature_count"]):
        raise RuntimeError(
            f"candidate {candidate_key} route-signature mismatch: "
            f"{route_signature_count}"
        )
    cross_gamma_spread = _cross_gamma_spread(paths)
    if cross_gamma_spread < 0.5:
        raise RuntimeError(
            f"candidate {candidate_key} lacks declared route spread: "
            f"{cross_gamma_spread:.6f}"
        )

    fig = plt.figure(figsize=(13.2, 5.7), facecolor="white")
    axis_3d = fig.add_subplot(1, 2, 1, projection="3d")
    axis_top = fig.add_subplot(1, 2, 2)
    _draw_cylinders(
        axis_3d, cylinders, config.taskspace.bounds[2], physical_radius,
    )
    _draw_cylinders_top(
        axis_top, cylinders, physical_radius=physical_radius,
    )
    for gamma, path in zip(GAMMAS, paths):
        label = rf"$\gamma={gamma:g}$"
        axis_3d.plot(
            path[:, 0], path[:, 1], path[:, 2],
            color=GAMMA_COLORS[gamma], linewidth=2.7, label=label,
        )
        axis_top.plot(
            path[:, 0], path[:, 1],
            color=GAMMA_COLORS[gamma], linewidth=2.7, label=label,
        )
    _start_goal(axis_3d, config)
    _style_axis(axis_3d, config)
    axis_3d.set_box_aspect(
        tuple(config.taskspace.bounds[:, 1] - config.taskspace.bounds[:, 0])
    )
    axis_3d.set_title("Perspective view", fontsize=13)
    _start_goal_top(axis_top, config)
    _style_top_axis(axis_top, config)
    axis_top.set_title("Top view", fontsize=13)
    axis_top.legend(loc="upper left", frameon=False, fontsize=10)
    fig.suptitle(
        f"SafeMPPI exact-five candidate {candidate_key} | all four succeed",
        fontsize=16,
        y=0.985,
    )
    fig.text(
        0.5, 0.012,
        "Gray: physical cylinders   Blue: robot-inflated model   "
        "One paired scene and rollout seed; qualitative evidence",
        ha="center", fontsize=9.5,
    )
    fig.tight_layout(rect=(0.0, 0.035, 1.0, 0.955))
    overlay = (
        output_dir / "assets" /
        f"cylinder_id_exact5_candidate_{candidate_key.lower()}_gamma_overlay.png"
    )
    _save_figure(fig, overlay)

    gif_rows = []
    for gamma, archive in zip(GAMMAS, archives):
        label = "1p0" if gamma == 1.0 else f"{gamma:.1f}".replace(".", "p")
        destination = (
            output_dir / "assets" /
            f"cylinder_id_exact5_candidate_{candidate_key.lower()}_nominal_g{label}.gif"
        )
        gif_rows.append({
            "gamma": gamma,
            **_nominal_polytope_gif(
                archive, destination, config, gamma=gamma,
                physical_radius=physical_radius,
                candidate_label=candidate_key,
            ),
        })
    return {
        "candidate": candidate_key,
        "scene_id": scene_id,
        "scene_hash": next(iter(scene_hashes)),
        "scene_bank_seed": 20_260_731,
        "scene_seed": int(archives[0]["scene_seed"]),
        "rollout_seed": rollout_seed,
        "cylinder_count": int(len(cylinders)),
        "route_signature_count": route_signature_count,
        "route_signatures": [list(signature) for signature in signatures],
        "cross_gamma_rms_spread_m": cross_gamma_spread,
        "minimum_clearance_m": min(row["min_clearance_m"] for row in rows),
        "all_success": True,
        "overlay_png": str(overlay.relative_to(output_dir)),
        "overlay_pdf": str(overlay.with_suffix(".pdf").relative_to(output_dir)),
        "rows": rows,
        "nominal_polytope_gifs": gif_rows,
    }


def _expert_overlays(
    handoff_dir: Path,
    output_dir: Path,
    config_path: Path,
) -> dict:
    candidates = [
        _expert_candidate(handoff_dir, output_dir, config_path, candidate)
        for candidate in EXACT_FIVE_CANDIDATES
    ]
    return {
        "evidence_contract": {
            "training_obstacle_count_range": [4, 8],
            "physical_lab_obstacle_count": 5,
            "paired_scene_and_rollout_seed_within_candidate": True,
            "selection_scope": (
                "184 exact-five, all-four-gamma-success scenes in the canonical "
                "2000-successes-per-gamma archive"
            ),
            "source_commit": "c46ae2fff7f77b920d38c2e249c43267f68504ca",
            "source_scene_bank_seed": 20_260_731,
            "selection_rule": (
                "maximize distinct obstacle-relative route signatures and "
                "cross-gamma route spread; retain only all-gamma terminal successes"
            ),
            "rate_estimate": False,
        },
        "candidates": candidates,
    }


def _raw_row(gamma: float, episode: int, seed: int, result: dict, config) -> dict:
    return {
        "gamma": float(gamma),
        "episode": int(episode),
        "seed": int(seed),
        "status": str(result["status"]),
        "steps": int(len(result["controls"])),
        "min_clearance_m": (
            None if result["min_clearance_m"] is None
            else float(result["min_clearance_m"])
        ),
        "window_validity": float(result["window_validity"]),
        "time_to_goal_s": (
            None if result["time_to_goal_s"] is None
            else float(result["time_to_goal_s"])
        ),
        "mode": result["mode"],
        "failure_point": _first_failure_point(result, config),
    }


def _save_rollout_npz(
    destination: Path,
    result: dict,
    *,
    gamma: float,
    seed: int,
    config_path: Path,
    checkpoint_path: Path,
    spheres: np.ndarray,
    scene_hash: str,
):
    destination.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        destination,
        states=np.asarray(result["states"], np.float32),
        controls=np.asarray(result["controls"], np.float32),
        executed_controls=np.asarray(result["applied_controls"], np.float32),
        dense_positions=_dense_path(result),
        gamma=np.asarray(gamma, np.float32),
        seed=np.asarray(seed, np.int64),
        status=np.asarray(result["status"]),
        sampling_temperature=np.asarray(1.0, np.float32),
        spheres=np.asarray(spheres, np.float32).reshape(-1, 4),
        scene_hash=np.asarray(scene_hash),
        config_sha256=np.asarray(_sha256(config_path)),
        checkpoint_sha256=np.asarray(_sha256(checkpoint_path)),
    )


def _stage1_raw_audit(
    policy,
    checkpoint_path: Path,
    output_dir: Path,
    config_path: Path,
    *,
    device: str,
) -> dict:
    config = load_config(config_path)
    spheres = np.asarray(config.obstacles.spheres, np.float32).reshape(-1, 4)
    results_by_gamma: dict[float, list[tuple[dict, dict]]] = {}
    rows = []
    selected = []
    counts = {key: 0 for key in EXPECTED_STAGE1_COUNTS}
    for gamma in GAMMAS:
        gamma_rows = []
        for episode in range(20):
            seed = 91_000 + 37 * episode
            result = raw_reference_rollout(
                policy,
                config,
                gamma,
                seed,
                device=device,
                sampling_temperature=1.0,
            )
            row = _raw_row(gamma, episode, seed, result, config)
            rows.append(row)
            gamma_rows.append((row, result))
            counts[row["status"]] = counts.get(row["status"], 0) + 1
        results_by_gamma[gamma] = gamma_rows
        successful = [item for item in gamma_rows if item[0]["status"] == "SUCCESS"]
        if successful:
            row, result = successful[0]
            label = "1" if gamma == 1.0 else f"{gamma:g}"
            destination = (
                output_dir / "trajectory_archives"
                / f"stage1_single_sphere_raw_g{label}_s{row['seed']}_success.npz"
            )
            _save_rollout_npz(
                destination,
                result,
                gamma=gamma,
                seed=row["seed"],
                config_path=config_path,
                checkpoint_path=checkpoint_path,
                spheres=spheres,
                scene_hash="fixed_stage1_single_sphere",
            )
            selected.append({
                "gamma": gamma,
                "episode": row["episode"],
                "seed": row["seed"],
                "archive": str(destination.relative_to(output_dir)),
                "archive_sha256": _sha256(destination),
            })
    if counts != EXPECTED_STAGE1_COUNTS:
        raise RuntimeError(
            f"Stage-1 raw audit changed: expected {EXPECTED_STAGE1_COUNTS}, got {counts}"
        )

    fig = plt.figure(figsize=(14.2, 10.0))
    for index, gamma in enumerate(GAMMAS):
        axis = fig.add_subplot(2, 2, index + 1, projection="3d")
        _draw_spheres(axis, spheres, physical_radius=0.254)
        for row, result in results_by_gamma[gamma]:
            path = _dense_path(result)
            if row["status"] == "SUCCESS":
                color, alpha, width = GAMMA_COLORS[gamma], 0.92, 2.0
            elif row["status"] == "COLLISION":
                color, alpha, width = "#c43c2f", 0.33, 0.9
            elif row["status"] == "OOB":
                color, alpha, width = "#e67e22", 0.45, 1.0
            else:
                color, alpha, width = "#777777", 0.32, 0.9
            axis.plot(path[:, 0], path[:, 1], path[:, 2], color=color,
                      alpha=alpha, linewidth=width)
            if row["failure_point"] is not None:
                axis.scatter(
                    *row["failure_point"], marker="x", s=35,
                    color="#a50026", linewidth=1.25, depthshade=False,
                )
        _start_goal(axis, config)
        _style_axis(axis, config, elev=20.0, azim=-56.0)
        local_counts = {
            status: sum(row["status"] == status for row, _ in results_by_gamma[gamma])
            for status in ("SUCCESS", "COLLISION", "OOB")
        }
        axis.set_title(
            rf"$\gamma={gamma:g}$   "
            f"S {local_counts['SUCCESS']} / C {local_counts['COLLISION']} / "
            f"OOB {local_counts['OOB']}",
            fontsize=13,
        )
    fig.suptitle(
        "Pretrained policy on the fixed midpoint sphere | raw temperature 1",
        fontsize=17,
        y=0.985,
    )
    fig.text(
        0.5, 0.018,
        "M=20 per gamma; colored paths succeed, muted red paths collide, red X marks first failure",
        ha="center", fontsize=10,
    )
    fig.tight_layout(rect=(0.0, 0.035, 1.0, 0.965))
    _save_figure(fig, output_dir / "assets/single_sphere_pretrained_r0_overlay.png")
    return {
        "contract": {
            "episodes_per_gamma": 20,
            "sampling_temperature": 1.0,
            "seed_formula": "91000 + 37 * episode",
            "controller": "canonical raw_reference_rollout",
            "uncertainty_tilting": False,
            "verifier_controller": False,
        },
        "counts": counts,
        "pooled": {
            "SR": counts["SUCCESS"] / 80.0,
            "CR": counts["COLLISION"] / 80.0,
            "OOB": counts["OOB"] / 80.0,
        },
        "per_gamma": [{
            "gamma": gamma,
            "SR": sum(row["status"] == "SUCCESS" for row, _ in results_by_gamma[gamma]) / 20.0,
            "CR": sum(row["status"] == "COLLISION" for row, _ in results_by_gamma[gamma]) / 20.0,
            "OOB": sum(row["status"] == "OOB" for row, _ in results_by_gamma[gamma]) / 20.0,
            "mean_window_validity": float(np.mean([
                row["window_validity"] for row, _ in results_by_gamma[gamma]
            ])),
        } for gamma in GAMMAS],
        "rows": rows,
        "selected_deployable_successes": selected,
    }


def _three_sphere_failure(
    policy,
    checkpoint_path: Path,
    output_dir: Path,
    config_path: Path,
    *,
    device: str,
) -> dict:
    config = load_config(config_path)
    scene = path_focused_scene_bank(config, 43, seed=191_000)[42]
    if len(scene.spheres) != 3 or scene.scene_hash != EXPECTED_THREE_SPHERE_HASH:
        raise RuntimeError(
            "three-sphere scene contract changed: "
            f"count={len(scene.spheres)}, hash={scene.scene_hash}"
        )
    scene_config = config_for_scene(config, scene)
    spheres = np.asarray(scene.spheres, np.float32).reshape(-1, 4)
    archive_dir = output_dir / "trajectory_archives"
    archive_dir.mkdir(parents=True, exist_ok=True)
    scene_json = archive_dir / "three_sphere_scene_seed191000_episode42.json"
    scene_payload = {
        "scene_bank_seed": 191_000,
        "episode": 42,
        "scene_seed": int(scene.seed),
        "scene_hash": scene.scene_hash,
        "spheres": spheres.tolist(),
    }
    scene_json.write_text(json.dumps(scene_payload, indent=2) + "\n")

    rows_and_results = []
    for gamma in GAMMAS:
        result = raw_reference_rollout(
            policy,
            scene_config,
            gamma,
            192_554,
            device=device,
            sampling_temperature=1.0,
        )
        row = _raw_row(gamma, 42, 192_554, result, scene_config)
        if row["status"] != "COLLISION":
            raise RuntimeError(
                f"expected fixed three-sphere collision at gamma={gamma}, got {row['status']}"
            )
        label = "1" if gamma == 1.0 else f"{gamma:g}"
        destination = archive_dir / f"three_sphere_ood_raw_g{label}_s192554_collision.npz"
        _save_rollout_npz(
            destination,
            result,
            gamma=gamma,
            seed=192_554,
            config_path=config_path,
            checkpoint_path=checkpoint_path,
            spheres=spheres,
            scene_hash=scene.scene_hash,
        )
        row["archive"] = str(destination.relative_to(output_dir))
        row["archive_sha256"] = _sha256(destination)
        rows_and_results.append((row, result))

    fig = plt.figure(figsize=(14.2, 10.0))
    for index, (row, result) in enumerate(rows_and_results):
        gamma = float(row["gamma"])
        axis = fig.add_subplot(2, 2, index + 1, projection="3d")
        _draw_spheres(axis, spheres, physical_radius=0.254)
        path = _dense_path(result)
        axis.plot(
            path[:, 0], path[:, 1], path[:, 2],
            color=GAMMA_COLORS[gamma], linewidth=2.5,
        )
        axis.scatter(
            *row["failure_point"], marker="x", s=78, color="#a50026",
            linewidth=2.0, depthshade=False,
        )
        _start_goal(axis, scene_config)
        _style_axis(axis, scene_config, elev=22.0, azim=-56.0)
        axis.set_title(
            rf"$\gamma={gamma:g}$   COLLISION",
            fontsize=13,
        )
    fig.suptitle(
        "Pretrained policy on a path-focused three-sphere OOD scene",
        fontsize=17,
        y=0.985,
    )
    fig.text(
        0.5, 0.018,
        "Fixed scene bank seed 191000, episode 42; raw seed 192554; red X marks first collision",
        ha="center", fontsize=10,
    )
    fig.tight_layout(rect=(0.0, 0.035, 1.0, 0.965))
    _save_figure(fig, output_dir / "assets/three_sphere_ood_failure_overlay.png")
    return {
        "contract": {
            "scene_bank_seed": 191_000,
            "episode": 42,
            "rollout_seed": 192_554,
            "sampling_temperature": 1.0,
            "controller": "canonical raw_reference_rollout",
        },
        "scene": {
            **scene_payload,
            "scene_json": str(scene_json.relative_to(output_dir)),
            "scene_json_sha256": _sha256(scene_json),
        },
        "all_collision": True,
        "rows": [row for row, _ in rows_and_results],
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--handoff-dir",
        type=Path,
        default=ROOT / "flow_deployment/minhyuk_stage1_handoff",
        help="Source handoff folder containing checkpoint and expert NPZ files.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        help="Destination; defaults to --handoff-dir.",
    )
    parser.add_argument("--device", default="cpu")
    parser.add_argument(
        "--cylinder-only",
        action="store_true",
        help=(
            "Regenerate exact-five cylinder evidence while preserving the "
            "already-qualified Stage-1 and three-sphere records."
        ),
    )
    args = parser.parse_args()
    handoff_dir = args.handoff_dir.resolve()
    output_dir = (args.output_dir or handoff_dir).resolve()
    (output_dir / "assets").mkdir(parents=True, exist_ok=True)
    (output_dir / "trajectory_archives").mkdir(parents=True, exist_ok=True)

    checkpoint_path = handoff_dir / "checkpoints/hp100_t128_d3.pt"
    cylinder_training_config = (
        ROOT / "configs/lab_clutter_cylinders_path_midpoint_uniform_v2.json"
    )
    cylinder_lab_config = ROOT / "configs/lab_clutter_cylinders_lab_five_v2.json"
    stage1_config = ROOT / "configs/lab_ball_stage1_t128.json"
    sphere_config = ROOT / "configs/lab_clutter_spheres_path_midpoint_uniform_v2.json"
    for path in (
        checkpoint_path, cylinder_training_config, cylinder_lab_config,
        stage1_config, sphere_config,
    ):
        if not path.is_file():
            raise FileNotFoundError(path)

    torch.manual_seed(0)
    policy = load_lab_reference_policy(checkpoint_path).to(args.device).eval()
    expert = _expert_overlays(handoff_dir, output_dir, cylinder_lab_config)
    if args.cylinder_only:
        existing_manifest_path = output_dir / "asset_manifest.json"
        if not existing_manifest_path.is_file():
            raise FileNotFoundError(existing_manifest_path)
        existing_manifest = json.loads(existing_manifest_path.read_text())
        stage1 = existing_manifest["stage1_single_sphere_pretrained"]
        three_sphere = existing_manifest["three_sphere_ood_pretrained"]
    else:
        stage1 = _stage1_raw_audit(
            policy, checkpoint_path, output_dir, stage1_config,
            device=args.device,
        )
        three_sphere = _three_sphere_failure(
            policy, checkpoint_path, output_dir, sphere_config,
            device=args.device,
        )

    generated = sorted([
        *[path for path in (output_dir / "assets").glob("*") if path.is_file()],
        *[
            path for path in (output_dir / "trajectory_archives").glob("*")
            if path.is_file() and (
                path.name.startswith("run_g")
                or path.name.startswith("stage1_single_sphere_")
                or path.name.startswith("three_sphere_")
            )
        ],
    ])
    manifest = {
        "status": "MINHYUK_STAGE1_HANDOFF_ASSETS_COMPLETE",
        "scientific_scope": (
            "Actual trajectory visualization and raw-policy qualification; "
            "no trajectory was fabricated. Exact-five candidates E/F are "
            "declared qualitative route-diversity selections, not rate estimates."
        ),
        "source": {
            "repository_head": _git_revision("HEAD"),
            "path_focused_source_commit": _git_revision(
                "origin/agent/path-focused-clutter-v2"
            ),
            "builder": str(Path(__file__).resolve().relative_to(ROOT)),
            "builder_sha256": _sha256(Path(__file__).resolve()),
            "checkpoint": str(checkpoint_path.relative_to(ROOT)),
            "checkpoint_sha256": _sha256(checkpoint_path),
            "configs": {
                str(path.relative_to(ROOT)): _sha256(path)
                for path in (
                    cylinder_training_config, cylinder_lab_config,
                    stage1_config, sphere_config,
                )
            },
        },
        "command": (
            "python scripts/build_minhyuk_stage1_handoff_assets.py "
            "--device cpu" + (" --cylinder-only" if args.cylinder_only else "")
        ),
        "id_cylinder_safemppi": expert,
        "stage1_single_sphere_pretrained": stage1,
        "three_sphere_ood_pretrained": three_sphere,
        "generated_files": [{
            "path": str(path.relative_to(output_dir)),
            "bytes": path.stat().st_size,
            "sha256": _sha256(path),
        } for path in generated],
    }
    destination = output_dir / "asset_manifest.json"
    destination.write_text(json.dumps(manifest, indent=2) + "\n")
    _write_handoff_checksums(output_dir)
    print(json.dumps({
        "status": manifest["status"],
        "stage1_pooled": stage1["pooled"],
        "stage1_counts": stage1["counts"],
        "three_sphere_all_collision": three_sphere["all_collision"],
        "output": str(output_dir),
    }, indent=2))


if __name__ == "__main__":
    main()
