#!/usr/bin/env python3
"""Build provenance-bound Stage-1 handoff trajectory figures for Minhyuk.

The script is intentionally evaluation-only.  It replays the promoted visual
checkpoint with the canonical raw temperature-1 controller and renders only
trajectories that were actually generated by the checked-in implementation.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from itertools import combinations
from pathlib import Path
import subprocess
import sys

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import torch


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from safe_mppi.config import load_config  # noqa: E402
from safe_mppi.environment import TaskEnvironment  # noqa: E402
from safe_mppi.lab_clutter import config_for_scene  # noqa: E402
from safe_mppi.lab_reference_flow_task import raw_reference_rollout  # noqa: E402
from safe_mppi.lab_visual_flow import load_lab_reference_policy  # noqa: E402
from safe_mppi.path_focused_clutter import path_focused_scene_bank  # noqa: E402


GAMMAS = (0.1, 0.3, 0.5, 1.0)
GAMMA_COLORS = {
    gamma: plt.get_cmap("plasma")(0.08 + 0.84 * index / 3.0)
    for index, gamma in enumerate(GAMMAS)
}
EXPECTED_STAGE1_COUNTS = {
    "SUCCESS": 11,
    "COLLISION": 64,
    "OOB": 5,
    "TIMEOUT": 0,
}
EXPECTED_THREE_SPHERE_HASH = (
    "82eb7361927f8d076a6a7fc7a3f52e17f4ff9d203b4af49ca532ceffa2afd0c3"
)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _git_revision(ref: str) -> str | None:
    completed = subprocess.run(
        ["git", "rev-parse", ref],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    return completed.stdout.strip() if completed.returncode == 0 else None


def _dense_path(result: dict) -> np.ndarray:
    states = np.asarray(result["states"], np.float32)
    dense = np.asarray(result["dense_steps"], np.float32)
    if not len(dense):
        return states[:, :3]
    return np.concatenate([states[:1, :3], dense.reshape(-1, 3)])


def _first_failure_point(result: dict, config) -> list[float] | None:
    if result["status"] == "SUCCESS":
        return None
    path = _dense_path(result)
    env = TaskEnvironment(config)
    if result["status"] == "COLLISION":
        clearance = env.obstacle_clearance(path)
        indices = np.flatnonzero(np.isfinite(clearance) & (clearance < 0.0))
    elif result["status"] == "OOB":
        indices = np.flatnonzero(~env.inside_taskspace(path))
    else:
        indices = np.asarray([len(path) - 1], dtype=np.int64)
    index = int(indices[0]) if len(indices) else len(path) - 1
    return [float(value) for value in path[index]]


def _arc_resample(path: np.ndarray, count: int = 96) -> np.ndarray:
    path = np.asarray(path, np.float64).reshape(-1, 3)
    keep = np.r_[True, np.linalg.norm(np.diff(path, axis=0), axis=1) > 1e-10]
    path = path[keep]
    if len(path) == 1:
        return np.repeat(path, count, axis=0)
    distance = np.r_[0.0, np.cumsum(np.linalg.norm(np.diff(path, axis=0), axis=1))]
    query = np.linspace(0.0, distance[-1], count)
    return np.column_stack([
        np.interp(query, distance, path[:, axis]) for axis in range(3)
    ])


def _cross_gamma_spread(paths: list[np.ndarray]) -> float:
    sampled = [_arc_resample(path) for path in paths]
    values = [
        np.sqrt(np.mean(np.sum((sampled[left] - sampled[right]) ** 2, axis=1)))
        for left, right in combinations(range(len(sampled)), 2)
    ]
    return float(np.mean(values))


def _draw_cylinders(axis, cylinders: np.ndarray, z_bounds, physical_radius: float):
    theta = np.linspace(0.0, 2.0 * np.pi, 36)
    theta_grid, z_grid = np.meshgrid(theta, np.asarray(z_bounds, np.float64))
    for x, y, modeled_radius in np.asarray(cylinders, np.float64).reshape(-1, 3):
        axis.plot_wireframe(
            x + modeled_radius * np.cos(theta_grid),
            y + modeled_radius * np.sin(theta_grid),
            z_grid,
            color="#2b8cbe",
            alpha=0.30,
            linewidth=0.55,
        )
        axis.plot_surface(
            x + physical_radius * np.cos(theta_grid),
            y + physical_radius * np.sin(theta_grid),
            z_grid,
            color="#747b80",
            alpha=0.62,
            linewidth=0.0,
            shade=True,
        )


def _draw_spheres(axis, spheres: np.ndarray, physical_radius: float):
    azimuth = np.linspace(0.0, 2.0 * np.pi, 32)
    polar = np.linspace(0.0, np.pi, 18)
    unit_x = np.outer(np.cos(azimuth), np.sin(polar))
    unit_y = np.outer(np.sin(azimuth), np.sin(polar))
    unit_z = np.outer(np.ones_like(azimuth), np.cos(polar))
    for x, y, z, modeled_radius in np.asarray(spheres, np.float64).reshape(-1, 4):
        axis.plot_wireframe(
            x + modeled_radius * unit_x,
            y + modeled_radius * unit_y,
            z + modeled_radius * unit_z,
            color="#2b8cbe",
            alpha=0.32,
            linewidth=0.5,
        )
        axis.plot_surface(
            x + physical_radius * unit_x,
            y + physical_radius * unit_y,
            z + physical_radius * unit_z,
            color="#747b80",
            alpha=0.66,
            linewidth=0.0,
            shade=True,
        )


def _style_axis(axis, config, *, elev: float = 25.0, azim: float = -57.0):
    axis.set(
        xlim=config.taskspace.bounds[0],
        ylim=config.taskspace.bounds[1],
        zlim=config.taskspace.bounds[2],
        xlabel=r"$x$ [m]",
        ylabel=r"$y$ [m]",
        zlabel=r"$z$ [m]",
    )
    axis.view_init(elev=elev, azim=azim)
    axis.grid(alpha=0.18)
    axis.tick_params(labelsize=8)


def _start_goal(axis, config):
    axis.scatter(
        *config.taskspace.start[:3], marker="s", s=42, color="black",
        depthshade=False, zorder=20,
    )
    axis.scatter(
        *config.taskspace.goal, marker="*", s=145, color="#f1c40f",
        edgecolor="black", linewidth=0.7, depthshade=False, zorder=20,
    )


def _save_figure(fig, destination: Path):
    destination.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(destination, dpi=210, bbox_inches="tight")
    fig.savefig(
        destination.with_suffix(".pdf"),
        bbox_inches="tight",
        metadata={"Creator": "safeMPPI_demo_3d", "CreationDate": None},
    )
    plt.close(fig)


def _expert_overlay(handoff_dir: Path, output_dir: Path, config_path: Path) -> dict:
    config = load_config(config_path)
    archive_dir = handoff_dir / "trajectory_archives"
    rows = []
    paths = []
    scene_hashes = set()
    cylinders = None
    for gamma in GAMMAS:
        label = "1" if gamma == 1.0 else f"{gamma:g}"
        path = archive_dir / f"run_g{label}_cylinders_00051_s461459.npz"
        with np.load(path, allow_pickle=True) as data:
            dense = np.asarray(data["dense_positions"], np.float32)
            current_cylinders = np.asarray(data["cylinders"], np.float32)
            goal_distance = float(np.linalg.norm(dense[-1] - config.taskspace.goal))
            status = "SUCCESS" if goal_distance <= config.taskspace.reach_radius else "FAILURE"
            if status != "SUCCESS":
                raise RuntimeError(f"expert archive did not reach the goal: {path}")
            if not np.isclose(float(data["gamma"]), gamma, atol=2e-7):
                raise RuntimeError(f"expert archive gamma mismatch: {path}")
            scene_hashes.add(str(data["scene_hash"].item()))
            if cylinders is None:
                cylinders = current_cylinders
            elif not np.array_equal(cylinders, current_cylinders):
                raise RuntimeError("expert overlay archives do not share one scene")
            paths.append(dense)
            rows.append({
                "gamma": gamma,
                "status": status,
                "seed": int(data["seed"]),
                "scene_id": str(data["scene_id"].item()),
                "scene_hash": str(data["scene_hash"].item()),
                "steps": int(len(data["controls"])),
                "time_to_goal_s": float(len(data["controls"]) * config.safemppi.dt),
                "goal_distance_m": goal_distance,
                "archive": str(path.relative_to(ROOT)),
                "archive_sha256": _sha256(path),
            })
    if len(scene_hashes) != 1:
        raise RuntimeError("expert overlay archives have inconsistent scene hashes")

    physical_radius = float(config.raw["scene_randomization"]["physical_radius_m"])
    fig = plt.figure(figsize=(9.8, 7.3))
    axis = fig.add_subplot(111, projection="3d")
    _draw_cylinders(axis, cylinders, config.taskspace.bounds[2], physical_radius)
    for gamma, path in zip(GAMMAS, paths):
        axis.plot(
            path[:, 0], path[:, 1], path[:, 2],
            color=GAMMA_COLORS[gamma], linewidth=2.7,
            label=rf"$\gamma={gamma:g}$",
        )
    _start_goal(axis, config)
    _style_axis(axis, config)
    axis.legend(loc="upper left", frameon=False, fontsize=10)
    axis.set_title(
        "SafeMPPI cylinder-ID reference | fixed all-success scene",
        fontsize=14,
        pad=15,
    )
    fig.text(
        0.5, 0.015,
        "Gray: physical cylinders   Blue wireframe: robot-inflated model",
        ha="center", fontsize=10,
    )
    _save_figure(fig, output_dir / "assets/cylinder_id_safemppi_gamma_overlay.png")
    return {
        "scene_id": "cylinders_00051",
        "scene_hash": next(iter(scene_hashes)),
        "cross_gamma_rms_spread_m": _cross_gamma_spread(paths),
        "all_success": True,
        "rows": rows,
    }


def _raw_row(gamma: float, episode: int, seed: int, result: dict, config) -> dict:
    return {
        "gamma": float(gamma),
        "episode": int(episode),
        "seed": int(seed),
        "status": str(result["status"]),
        "steps": int(len(result["controls"])),
        "min_clearance_m": (
            None if result["min_clearance_m"] is None
            else float(result["min_clearance_m"])
        ),
        "window_validity": float(result["window_validity"]),
        "time_to_goal_s": (
            None if result["time_to_goal_s"] is None
            else float(result["time_to_goal_s"])
        ),
        "mode": result["mode"],
        "failure_point": _first_failure_point(result, config),
    }


def _save_rollout_npz(
    destination: Path,
    result: dict,
    *,
    gamma: float,
    seed: int,
    config_path: Path,
    checkpoint_path: Path,
    spheres: np.ndarray,
    scene_hash: str,
):
    destination.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        destination,
        states=np.asarray(result["states"], np.float32),
        controls=np.asarray(result["controls"], np.float32),
        executed_controls=np.asarray(result["applied_controls"], np.float32),
        dense_positions=_dense_path(result),
        gamma=np.asarray(gamma, np.float32),
        seed=np.asarray(seed, np.int64),
        status=np.asarray(result["status"]),
        sampling_temperature=np.asarray(1.0, np.float32),
        spheres=np.asarray(spheres, np.float32).reshape(-1, 4),
        scene_hash=np.asarray(scene_hash),
        config_sha256=np.asarray(_sha256(config_path)),
        checkpoint_sha256=np.asarray(_sha256(checkpoint_path)),
    )


def _stage1_raw_audit(
    policy,
    checkpoint_path: Path,
    output_dir: Path,
    config_path: Path,
    *,
    device: str,
) -> dict:
    config = load_config(config_path)
    spheres = np.asarray(config.obstacles.spheres, np.float32).reshape(-1, 4)
    results_by_gamma: dict[float, list[tuple[dict, dict]]] = {}
    rows = []
    selected = []
    counts = {key: 0 for key in EXPECTED_STAGE1_COUNTS}
    for gamma in GAMMAS:
        gamma_rows = []
        for episode in range(20):
            seed = 91_000 + 37 * episode
            result = raw_reference_rollout(
                policy,
                config,
                gamma,
                seed,
                device=device,
                sampling_temperature=1.0,
            )
            row = _raw_row(gamma, episode, seed, result, config)
            rows.append(row)
            gamma_rows.append((row, result))
            counts[row["status"]] = counts.get(row["status"], 0) + 1
        results_by_gamma[gamma] = gamma_rows
        successful = [item for item in gamma_rows if item[0]["status"] == "SUCCESS"]
        if successful:
            row, result = successful[0]
            label = "1" if gamma == 1.0 else f"{gamma:g}"
            destination = (
                output_dir / "trajectory_archives"
                / f"stage1_single_sphere_raw_g{label}_s{row['seed']}_success.npz"
            )
            _save_rollout_npz(
                destination,
                result,
                gamma=gamma,
                seed=row["seed"],
                config_path=config_path,
                checkpoint_path=checkpoint_path,
                spheres=spheres,
                scene_hash="fixed_stage1_single_sphere",
            )
            selected.append({
                "gamma": gamma,
                "episode": row["episode"],
                "seed": row["seed"],
                "archive": str(destination.relative_to(output_dir)),
                "archive_sha256": _sha256(destination),
            })
    if counts != EXPECTED_STAGE1_COUNTS:
        raise RuntimeError(
            f"Stage-1 raw audit changed: expected {EXPECTED_STAGE1_COUNTS}, got {counts}"
        )

    fig = plt.figure(figsize=(14.2, 10.0))
    for index, gamma in enumerate(GAMMAS):
        axis = fig.add_subplot(2, 2, index + 1, projection="3d")
        _draw_spheres(axis, spheres, physical_radius=0.254)
        for row, result in results_by_gamma[gamma]:
            path = _dense_path(result)
            if row["status"] == "SUCCESS":
                color, alpha, width = GAMMA_COLORS[gamma], 0.92, 2.0
            elif row["status"] == "COLLISION":
                color, alpha, width = "#c43c2f", 0.33, 0.9
            elif row["status"] == "OOB":
                color, alpha, width = "#e67e22", 0.45, 1.0
            else:
                color, alpha, width = "#777777", 0.32, 0.9
            axis.plot(path[:, 0], path[:, 1], path[:, 2], color=color,
                      alpha=alpha, linewidth=width)
            if row["failure_point"] is not None:
                axis.scatter(
                    *row["failure_point"], marker="x", s=35,
                    color="#a50026", linewidth=1.25, depthshade=False,
                )
        _start_goal(axis, config)
        _style_axis(axis, config, elev=20.0, azim=-56.0)
        local_counts = {
            status: sum(row["status"] == status for row, _ in results_by_gamma[gamma])
            for status in ("SUCCESS", "COLLISION", "OOB")
        }
        axis.set_title(
            rf"$\gamma={gamma:g}$   "
            f"S {local_counts['SUCCESS']} / C {local_counts['COLLISION']} / "
            f"OOB {local_counts['OOB']}",
            fontsize=13,
        )
    fig.suptitle(
        "Pretrained policy on the fixed midpoint sphere | raw temperature 1",
        fontsize=17,
        y=0.985,
    )
    fig.text(
        0.5, 0.018,
        "M=20 per gamma; colored paths succeed, muted red paths collide, red X marks first failure",
        ha="center", fontsize=10,
    )
    fig.tight_layout(rect=(0.0, 0.035, 1.0, 0.965))
    _save_figure(fig, output_dir / "assets/single_sphere_pretrained_r0_overlay.png")
    return {
        "contract": {
            "episodes_per_gamma": 20,
            "sampling_temperature": 1.0,
            "seed_formula": "91000 + 37 * episode",
            "controller": "canonical raw_reference_rollout",
            "uncertainty_tilting": False,
            "verifier_controller": False,
        },
        "counts": counts,
        "pooled": {
            "SR": counts["SUCCESS"] / 80.0,
            "CR": counts["COLLISION"] / 80.0,
            "OOB": counts["OOB"] / 80.0,
        },
        "per_gamma": [{
            "gamma": gamma,
            "SR": sum(row["status"] == "SUCCESS" for row, _ in results_by_gamma[gamma]) / 20.0,
            "CR": sum(row["status"] == "COLLISION" for row, _ in results_by_gamma[gamma]) / 20.0,
            "OOB": sum(row["status"] == "OOB" for row, _ in results_by_gamma[gamma]) / 20.0,
            "mean_window_validity": float(np.mean([
                row["window_validity"] for row, _ in results_by_gamma[gamma]
            ])),
        } for gamma in GAMMAS],
        "rows": rows,
        "selected_deployable_successes": selected,
    }


def _three_sphere_failure(
    policy,
    checkpoint_path: Path,
    output_dir: Path,
    config_path: Path,
    *,
    device: str,
) -> dict:
    config = load_config(config_path)
    scene = path_focused_scene_bank(config, 43, seed=191_000)[42]
    if len(scene.spheres) != 3 or scene.scene_hash != EXPECTED_THREE_SPHERE_HASH:
        raise RuntimeError(
            "three-sphere scene contract changed: "
            f"count={len(scene.spheres)}, hash={scene.scene_hash}"
        )
    scene_config = config_for_scene(config, scene)
    spheres = np.asarray(scene.spheres, np.float32).reshape(-1, 4)
    archive_dir = output_dir / "trajectory_archives"
    archive_dir.mkdir(parents=True, exist_ok=True)
    scene_json = archive_dir / "three_sphere_scene_seed191000_episode42.json"
    scene_payload = {
        "scene_bank_seed": 191_000,
        "episode": 42,
        "scene_seed": int(scene.seed),
        "scene_hash": scene.scene_hash,
        "spheres": spheres.tolist(),
    }
    scene_json.write_text(json.dumps(scene_payload, indent=2) + "\n")

    rows_and_results = []
    for gamma in GAMMAS:
        result = raw_reference_rollout(
            policy,
            scene_config,
            gamma,
            192_554,
            device=device,
            sampling_temperature=1.0,
        )
        row = _raw_row(gamma, 42, 192_554, result, scene_config)
        if row["status"] != "COLLISION":
            raise RuntimeError(
                f"expected fixed three-sphere collision at gamma={gamma}, got {row['status']}"
            )
        label = "1" if gamma == 1.0 else f"{gamma:g}"
        destination = archive_dir / f"three_sphere_ood_raw_g{label}_s192554_collision.npz"
        _save_rollout_npz(
            destination,
            result,
            gamma=gamma,
            seed=192_554,
            config_path=config_path,
            checkpoint_path=checkpoint_path,
            spheres=spheres,
            scene_hash=scene.scene_hash,
        )
        row["archive"] = str(destination.relative_to(output_dir))
        row["archive_sha256"] = _sha256(destination)
        rows_and_results.append((row, result))

    fig = plt.figure(figsize=(14.2, 10.0))
    for index, (row, result) in enumerate(rows_and_results):
        gamma = float(row["gamma"])
        axis = fig.add_subplot(2, 2, index + 1, projection="3d")
        _draw_spheres(axis, spheres, physical_radius=0.254)
        path = _dense_path(result)
        axis.plot(
            path[:, 0], path[:, 1], path[:, 2],
            color=GAMMA_COLORS[gamma], linewidth=2.5,
        )
        axis.scatter(
            *row["failure_point"], marker="x", s=78, color="#a50026",
            linewidth=2.0, depthshade=False,
        )
        _start_goal(axis, scene_config)
        _style_axis(axis, scene_config, elev=22.0, azim=-56.0)
        axis.set_title(
            rf"$\gamma={gamma:g}$   COLLISION",
            fontsize=13,
        )
    fig.suptitle(
        "Pretrained policy on a path-focused three-sphere OOD scene",
        fontsize=17,
        y=0.985,
    )
    fig.text(
        0.5, 0.018,
        "Fixed scene bank seed 191000, episode 42; raw seed 192554; red X marks first collision",
        ha="center", fontsize=10,
    )
    fig.tight_layout(rect=(0.0, 0.035, 1.0, 0.965))
    _save_figure(fig, output_dir / "assets/three_sphere_ood_failure_overlay.png")
    return {
        "contract": {
            "scene_bank_seed": 191_000,
            "episode": 42,
            "rollout_seed": 192_554,
            "sampling_temperature": 1.0,
            "controller": "canonical raw_reference_rollout",
        },
        "scene": {
            **scene_payload,
            "scene_json": str(scene_json.relative_to(output_dir)),
            "scene_json_sha256": _sha256(scene_json),
        },
        "all_collision": True,
        "rows": [row for row, _ in rows_and_results],
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--handoff-dir",
        type=Path,
        default=ROOT / "flow_deployment/minhyuk_stage1_handoff",
        help="Source handoff folder containing checkpoint and expert NPZ files.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        help="Destination; defaults to --handoff-dir.",
    )
    parser.add_argument("--device", default="cpu")
    args = parser.parse_args()
    handoff_dir = args.handoff_dir.resolve()
    output_dir = (args.output_dir or handoff_dir).resolve()
    (output_dir / "assets").mkdir(parents=True, exist_ok=True)
    (output_dir / "trajectory_archives").mkdir(parents=True, exist_ok=True)

    checkpoint_path = handoff_dir / "checkpoints/hp100_t128_d3.pt"
    cylinder_config = ROOT / "configs/lab_clutter_cylinders_path_midpoint_uniform_v2.json"
    stage1_config = ROOT / "configs/lab_ball_stage1_t128.json"
    sphere_config = ROOT / "configs/lab_clutter_spheres_path_midpoint_uniform_v2.json"
    for path in (checkpoint_path, cylinder_config, stage1_config, sphere_config):
        if not path.is_file():
            raise FileNotFoundError(path)

    torch.manual_seed(0)
    policy = load_lab_reference_policy(checkpoint_path).to(args.device).eval()
    expert = _expert_overlay(handoff_dir, output_dir, cylinder_config)
    stage1 = _stage1_raw_audit(
        policy, checkpoint_path, output_dir, stage1_config, device=args.device,
    )
    three_sphere = _three_sphere_failure(
        policy, checkpoint_path, output_dir, sphere_config, device=args.device,
    )

    generated = sorted([
        *[path for path in (output_dir / "assets").glob("*") if path.is_file()],
        *[
            path for path in (output_dir / "trajectory_archives").glob("*")
            if path.is_file() and (
                path.name.startswith("stage1_single_sphere_")
                or path.name.startswith("three_sphere_")
            )
        ],
    ])
    manifest = {
        "status": "MINHYUK_STAGE1_HANDOFF_ASSETS_COMPLETE",
        "scientific_scope": (
            "Actual trajectory visualization and raw-policy qualification; "
            "no trajectory was fabricated and no rate was visually curated."
        ),
        "source": {
            "repository_head": _git_revision("HEAD"),
            "path_focused_source_commit": _git_revision(
                "origin/agent/path-focused-clutter-v2"
            ),
            "builder": str(Path(__file__).resolve().relative_to(ROOT)),
            "builder_sha256": _sha256(Path(__file__).resolve()),
            "checkpoint": str(checkpoint_path.relative_to(ROOT)),
            "checkpoint_sha256": _sha256(checkpoint_path),
            "configs": {
                str(path.relative_to(ROOT)): _sha256(path)
                for path in (cylinder_config, stage1_config, sphere_config)
            },
        },
        "command": (
            "python scripts/build_minhyuk_stage1_handoff_assets.py "
            "--device cpu"
        ),
        "id_cylinder_safemppi": expert,
        "stage1_single_sphere_pretrained": stage1,
        "three_sphere_ood_pretrained": three_sphere,
        "generated_files": [{
            "path": str(path.relative_to(output_dir)),
            "bytes": path.stat().st_size,
            "sha256": _sha256(path),
        } for path in generated],
    }
    destination = output_dir / "asset_manifest.json"
    destination.write_text(json.dumps(manifest, indent=2) + "\n")
    print(json.dumps({
        "status": manifest["status"],
        "stage1_pooled": stage1["pooled"],
        "stage1_counts": stage1["counts"],
        "three_sphere_all_collision": three_sphere["all_collision"],
        "output": str(output_dir),
    }, indent=2))


if __name__ == "__main__":
    main()
